jenkins-practice

diff --git a/80-cdn/Jenkinsfile b/80-cdn/Jenkinsfile
--- a/80-cdn/Jenkinsfile
+++ b/80-cdn/Jenkinsfile
@@ -29,8 +29,8 @@ pipeline {
                 withAWS(region: "${env.AWS_REGION}", credentials: "${env.AWS_CREDS}") {
                     dir("${env.DIR}") {
                         sh '''
-                        terraform init -reconfigure
-                        terraform plan -out=tfplan
+                            terraform init -reconfigure
+                            terraform plan -out=tfplan
                         '''
                     }
                 }
@@ -45,28 +45,28 @@ pipeline {
                 withAWS(region: "${env.AWS_REGION}", credentials: "${env.AWS_CREDS}") {
                     dir("${env.DIR}") {
                         sh '''
-                        terraform apply -auto-approve tfplan
+                            terraform apply -auto-approve tfplan
                         '''
                     }
                 }
             }
         }
 
-        stage('Destroy Self (CDN)') {
-            when {
-                expression { params.ACTION == 'destroy' }
-            }
-            steps {
-                withAWS(region: "${env.AWS_REGION}", credentials: "${env.AWS_CREDS}") {
-                    dir("${env.DIR}") {
-                        sh '''
-                        terraform init -reconfigure
-                        terraform destroy -auto-approve
-                        '''
-                    }
-                }
-            }
-        }
+        // stage('Destroy Self (CDN)') {
+        //     when {
+        //         expression { params.ACTION == 'destroy' }
+        //     }
+        //     steps {
+        //         withAWS(region: "${env.AWS_REGION}", credentials: "${env.AWS_CREDS}") {
+        //             dir("${env.DIR}") {
+        //                 sh '''
+        //                 terraform init -reconfigure
+        //                 terraform destroy -auto-approve
+        //                 '''
+        //             }
+        //         }
+        //     }
+        // }
 
         stage('Destroy Dependencies') {
             when {
@@ -75,23 +75,25 @@ pipeline {
             steps {
                 echo 'Triggering destroy in reverse dependency order...'
                 script {
-                    def jobs = [
+                    def directories = [
+                        '80-cdn',
+                        '50-ecr',
                         '70-ingress-alb',
                         '60-acm',
-                        '50-ecr',
-                        '40-rds',
                         '40-eks',
+                        '40-rds',
                         '20-bastion',
                         '10-sg',
                         '00-vpc'
                     ]
-                    for (job in jobs) {
-                        catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
-                            echo "⛔ Triggering destroy for: ${job}"
-                            build job: job,
-                                  parameters: [string(name: 'ACTION', value: 'destroy')],
-                                  wait: true
-                        }
+                    for (dir in directories) {
+                        echo "Destroying resources in directory: ${dir}"
+                        sh """
+                            cd ${dir}
+                            terraform init -reconfigure
+                            terraform destroy -auto-approve || { echo "Failed to destroy resources in ${dir}"; exit 1; }
+                            cd ..
+                        """
                     }
                 }
             }
